services:
  - type: web
    name: e-commerce-app
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
    healthCheckPath: /healthz
