// app/layout.tsx or app/user/layout.tsx
import type { Metadata } from "next";
import "../globals.css";
import Header from "@/app/user/components/layout/Header/Header";
import HeaderCategorySelector from "./components/layout/HeaderCategorySelector/HeaderCategorySelector";
import { getCurrentSession } from "@/actions/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const UserLayout = async ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const { user } = await getCurrentSession();

  return (
    <div>
      <Header
        user={user}
        categorySelector={<HeaderCategorySelector />}
      />
      {children}
    </div>
  );
};

export default UserLayout;
